
"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd-fv#%rzzz@%nxg(evl1x0lv17(gyiq)wpz*b9_^qc9d*oorv@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*', '10.21.66.165'
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
)
CORS_ALLOW_CREDENTIALS = True
USE_TZ = False
BASE_URL = "http://10.0.0.12:8000/"
BASE_URL2 = "http://10.0.0.12/"
FILE_PATH = BASE_DIR+"\StudentId"
FILE_PATH_NEW = BASE_DIR+"\HostelId"

SESSION_COOKIE_HTTPONLY = False
 
# CORS_ORIGIN_WHITELIST = (
#     '*', '10.21.66.165'

# )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'bulk_update_or_create',
    # 'corsheaders',
    'musterroll',
    'leave',
    'dashboard',
    'attendance',
    'grievance',
    #'login_rest',
    'separation',
    'django_query_signals',
    'website',
    'Accounts',
    'aar',
    'StudentAccounts',
    'Registrar',
    'Redressal',
    'StudentHostel',
    'StudentFeedback',
    'StudentAcademics',
    'StudentPortal',
    'Ticketing',
    'StudentMMS',
    'StudentSMM',
    'Venue',
    'Achievement',
    'AppraisalStaff',
    'LessonPlan',
    'AppraisalFaculty',
    'DeptAchievement',
    'Store_data',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # z'django.middleware.csrf.CsrfViewMiddleware',
    'erp.middleware.middleware.LogAllMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

CONTENT_TYPES = ['jpeg', 'jpg', 'png', 'pdf']

MAX_UPLOAD_SIZE = "5242880"  # 5MB

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
# V9&1zN5vZ
DATABASES = {

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #     # 'HOST': '0.tcp.ngrok.io',
    #     'HOST': '10.0.0.12',
    #     'NAME': 'latest_erp2',
    #     'USER': 'new_root',
    #     'PASSWORD': 'Y9(1v*2zpTq',
    #     # 'PORT': '19528',
    #     'PORT': '3306',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'HOST': 'localhost',
        'NAME': 'new_erp',
        'USER': 'root',
        'PASSWORD': 'nimiatsami12@',
        'PORT': '3306',
    },
    # 'log_db': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #     'HOST': '10.0.0.12',
    #     'NAME': 'latest_erp_log_record',
    #     'USER': 'new_root',
    #     'PASSWORD': 'jayERP@357$',
    #     'PORT': '3306',
    # },
    # 'inno': 
    #         {
    #         'ENGINE': 'django.db.backends.mysql',
    #         'HOST': '10.0.0.12',
    #         'NAME': 'inno_19',
    #         'USER': 'new_root',
    #         'PASSWORD': 'Y9(1v*2zpTq',
    #         'PORT': '3306',
    #         # 'OPTIONS': {
    #         #   'init_command': "SET sql_mode ='STRICT_TRANS_TABLES'"
    #         #    }
    #         },



}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK_DOCS = {
    'HIDE_DOCS': True  # Default: False
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
    ),

    'DEFAULT_THROTTLE_RATES': {
        'anon': '2/day',

    },

    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ),

    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.AllowAny',
        #'rest_framework.permissions.IsAuthenticated',
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        #'rest_framework.permissions.DjangoModelPermissions',

    ]
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# SESSION EXPIRE AFTER 100 years
SESSION_COOKIE_AGE = 3155760000


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# print(STATIC_ROOT)


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")
# STATICFILES_DIRS = [

# os.path.join(BASE_DIR,"static"),
#]

#'/home/erp_v2/erp/lib/python2.7/site-packages/rest_framework_swagger/static
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media")
