# Generated by Django 2.0 on 2021-03-05 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__first__'),
        ('Registrar', '0008_auto_20210305_1829'),
        ('StudentAcademics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcadCoordinator_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_type', models.CharField(default=None, max_length=5)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTCord2021e_emp', to='login.EmployeePrimdetail')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTCoord_2021e', to='login.EmployeePrimdetail')),
                ('section', models.ForeignKey(db_column='section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TimeTableCoord_2021e_section', to='Registrar.Sections')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTCoord2021eSession', to='Registrar.Semtiming')),
            ],
            options={
                'db_table': 'StuAcadCoord_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AcademicsCalendar_2021e',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('color', models.CharField(db_column='color', max_length=20)),
                ('description', models.TextField(db_column='description', default=None, null=True)),
                ('status', models.CharField(db_column='status', default='INSERT', max_length=20)),
                ('type', models.ForeignKey(db_column='type', max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_academicsCalendar_2021e', to='StudentAcademics.StudentAcademicsDropdown')),
            ],
            options={
                'db_table': 'academicsCalendar_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attendance_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('lecture', models.IntegerField(default=1)),
                ('normal_remedial', models.CharField(default='N', max_length=5)),
                ('isgroup', models.CharField(default='N', max_length=5)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.CharField(default='N', max_length=2)),
                ('constrain_key', models.CharField(db_column='constrain_key', default=0, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AttEmp_2021e', to='login.EmployeePrimdetail')),
            ],
            options={
                'db_table': 'StuAcadAttendance_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmpGroupAssign_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StuGroup2_emp_2021e', to='login.EmployeePrimdetail')),
                ('emp_id', models.ForeignKey(db_column='Emp_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_grp_fee_emp_2021e', to='login.EmployeePrimdetail')),
            ],
            options={
                'db_table': 'EmpGroupAssign_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacultyTime_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_num', models.IntegerField()),
                ('day', models.IntegerField()),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('remark', models.CharField(default=None, max_length=20, null=True)),
                ('hod_remark', models.CharField(default=None, max_length=20, null=True)),
                ('hod_approval_time', models.DateTimeField(default=None, null=True)),
                ('hod_status', models.CharField(default='PENDING', max_length=20)),
                ('dean_remark', models.CharField(default=None, max_length=20, null=True)),
                ('dean_status', models.CharField(default='PENDING', max_length=20)),
                ('dean_approval_time', models.DateTimeField(default=None, null=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FacT2021e_emp', to='login.EmployeePrimdetail')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FacTime_2021e', to='login.EmployeePrimdetail')),
                ('section', models.ForeignKey(db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FacSec_2021e', to='Registrar.Sections')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FacTime2021eSession', to='Registrar.Semtiming')),
            ],
            options={
                'db_table': 'StuAcadFacTime_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupSection_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'StuAcadGroupSection_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LockingUnlocking_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_type', models.CharField(default='A', max_length=5)),
                ('att_date_from', models.DateField(default=None, null=True)),
                ('att_date_to', models.DateField(default=None, null=True)),
                ('unlock_from', models.DateTimeField(default=None, null=True)),
                ('unlock_to', models.DateTimeField(default=None, null=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('att_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LockAttType_2021e', to='StudentAcademics.StudentAcademicsDropdown')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LockEmp_2021e', to='login.EmployeePrimdetail')),
                ('section', models.ForeignKey(db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lock_2021e', to='Registrar.Sections')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lock2021eSession', to='Registrar.Semtiming')),
            ],
            options={
                'db_table': 'StuAcadLockingUnlocking_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionGroupDetails_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(default='INTER', max_length=20)),
                ('group_name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('type_of_group', models.CharField(default='ACADEMICS', max_length=20)),
                ('added_by', models.ForeignKey(db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Group2021e_emp', to='login.EmployeePrimdetail')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecDet2021eSession', to='Registrar.Semtiming')),
            ],
            options={
                'db_table': 'StuAcadGroupDetails_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentAttStatus_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_status', models.CharField(default='A', max_length=2)),
                ('approval_status', models.CharField(default=None, max_length=20, null=True)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(default=None, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_approved_by_2021e', to='login.EmployeePrimdetail')),
                ('att_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MarkAttCateg_2021e', to='StudentAcademics.StudentAcademicsDropdown')),
                ('att_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Att_id_2021e', to='StudentAcademics.Attendance_2021e')),
                ('att_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MarkAttType_2021e', to='StudentAcademics.StudentAcademicsDropdown')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_by_2021e', to='login.EmployeePrimdetail')),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_recommended_by_2021e', to='login.EmployeePrimdetail')),
                ('uniq_id', models.ForeignKey(db_column='Uniq_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Att_fee_uniq_2021e', to='Registrar.studentSession_2021e')),
            ],
            options={
                'db_table': 'StuAcadAttStatus_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StuGroupAssign_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StuGroup1_emp_2021e', to='login.EmployeePrimdetail')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GAS2021e', to='StudentAcademics.SectionGroupDetails_2021e')),
                ('uniq_id', models.ForeignKey(db_column='Uniq_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_grp_fee_uniq_2021e', to='Registrar.studentSession_2021e')),
            ],
            options={
                'db_table': 'StuGroupAssign_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_alpha_code', models.CharField(default=None, max_length=50, null=True)),
                ('sub_num_code', models.CharField(default=None, max_length=50, null=True)),
                ('sub_name', models.CharField(default=None, max_length=500, null=True)),
                ('max_ct_marks', models.FloatField()),
                ('max_ta_marks', models.FloatField()),
                ('max_att_marks', models.FloatField()),
                ('max_university_marks', models.FloatField()),
                ('no_of_units', models.IntegerField(default=0)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubInfo2021e_emp', to='login.EmployeePrimdetail')),
                ('sem', models.ForeignKey(db_column='Sem_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubInfo_2021e_sem', to='Registrar.StudentSemester')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubInfo2021eSession', to='Registrar.Semtiming')),
                ('subject_type', models.ForeignKey(db_column='Subject_Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubInfoSubType_2021e', to='Registrar.StudentDropdown')),
                ('subject_unit', models.ForeignKey(db_column='Subject_Unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubInfoSubUnit_2021e', to='Registrar.StudentDropdown')),
            ],
            options={
                'db_table': 'StuAcadSubjectInfo_2021e',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeTableSlots_2021e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('num_lecture_slots', models.IntegerField()),
                ('dean_approval_status', models.CharField(default='PENDING', max_length=20)),
                ('remark', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.CharField(default='INSERT', max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='Added_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TT2021e_emp', to='login.EmployeePrimdetail')),
                ('sem', models.ForeignKey(db_column='Sem_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TimeTableSlots_2021e_sem', to='Registrar.StudentSemester')),
                ('session', models.ForeignKey(db_column='session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TT2021eSession', to='Registrar.Semtiming')),
            ],
            options={
                'db_table': 'StuAcadTTSlots_2021e',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='groupsection_2021e',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GS2021e', to='StudentAcademics.SectionGroupDetails_2021e'),
        ),
        migrations.AddField(
            model_name='groupsection_2021e',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GS2021e', to='Registrar.Sections'),
        ),
        migrations.AddField(
            model_name='facultytime_2021e',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FacTimeSub_id_2021e', to='StudentAcademics.SubjectInfo_2021e'),
        ),
        migrations.AddField(
            model_name='empgroupassign_2021e',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GAE2021e', to='StudentAcademics.SectionGroupDetails_2021e'),
        ),
        migrations.AddField(
            model_name='attendance_2021e',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AttGid_2021e', to='StudentAcademics.SectionGroupDetails_2021e'),
        ),
        migrations.AddField(
            model_name='attendance_2021e',
            name='section',
            field=models.ForeignKey(db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Att_2021e', to='Registrar.Sections'),
        ),
        migrations.AddField(
            model_name='attendance_2021e',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AttSub_id_2021e', to='StudentAcademics.SubjectInfo_2021e'),
        ),
        migrations.AddField(
            model_name='acadcoordinator_2021e',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AcadCoordinator_2021e_sub', to='StudentAcademics.SubjectInfo_2021e'),
        ),
    ]
