from django.conf.urls import url

from aar.dept_achievemrnt import web_rnd_tabledata,DirReport,approval,Schools,website_aar,website_single,hobbyclub,IndustrialVisit,GuestLecture,EventsOrganized,Achievements,index,R_Conference,R_Guidence,R_journal,Book,Update_Conferance,Update_Journal,Update_Book,Update_Guidence,Lectures,Training,Projects,Patent_data,Update_Patent,Update_Lectures,Update_Training,Update_Projects,index_update,mou,aar_report,deanaar_report,report,director_report,director_department_report,delete_aar_employee,aar_dept_report,aar_emp_report,getComponents,emp_detail,locking_unlocking,aar_report_test,aar_hod_dept_report,update_departmental_aar,aar_approved_report,rnd_approval,aar_increment_settings,staff_shod,staff_sdir,staff_a,staff_ahod,staff_adir,staff_emg,staff_emg_submit,staff_emg_hod_dropdown,staff_emg_details,staff_emg_hod_submit,staff_emg_dir_dropdown,staff_emg_dir_details,staff_emg_dir_submit,staff_annual_increment_summary,staff_a_report,staff_ahod_report,staff_adir_report,staff_shod_report,staff_sdir_report,staff_emg_report,staff_emghod_report,staff_emgdir_report,aar_dir_advance_report,aar_dir_advance_report_data,aar_emp_end_report,rnd_update,rnd_reject,rnd_view,rnd_tabledata
# from aar.views import web_rnd_tabledata,DirReport,approval,Schools,website_aar,website_single,hobbyclub,IndustrialVisit,GuestLecture,EventsOrganized,Achievements,index,R_Conference,R_Guidence,R_journal,Book,Update_Conferance,Update_Journal,Update_Book,Update_Guidence,Lectures,Training,Projects,Patent_data,Update_Patent,Update_Lectures,Update_Training,Update_Projects,index_update,mou,aar_report,deanaar_report,report,director_report,director_department_report,delete_aar_employee,aar_dept_report,aar_emp_report,getComponents,emp_detail,locking_unlocking,aar_report_test,aar_hod_dept_report,update_departmental_aar,aar_approved_report,rnd_approval,aar_increment_settings,staff_shod,staff_sdir,staff_a,staff_ahod,staff_adir,staff_emg,staff_emg_submit,staff_emg_hod_dropdown,staff_emg_details,staff_emg_hod_submit,staff_emg_dir_dropdown,staff_emg_dir_details,staff_emg_dir_submit,staff_annual_increment_summary,staff_a_report,staff_ahod_report,staff_adir_report,staff_shod_report,staff_sdir_report,staff_emg_report,staff_emghod_report,staff_emgdir_report,aar_dir_advance_report,aar_dir_advance_report_data,aar_emp_end_report,rnd_update,rnd_reject,rnd_view,rnd_tabledata
from aar.views_faculty import form_data,insert_data,fc_app_advance_report,recommend


urlpatterns = [
    url(r'^books/$', index, name='index'),
    url(r'^update/$', index_update, name='index_update'),
    url(r'^insert/$',Book, name='Book'),
    url(r'^conferance/$',R_Conference, name='R_Conference'),
    url(r'^guidance/$',R_Guidence, name='R_Guidence'),
    url(r'^journal/$',R_journal, name='R_journal'),
    url(r'^update_conf/$',Update_Conferance),
    #url(r'^update_conf_dept/$',Update_Conferance_dept),
    url(r'^update_journal/$',Update_Journal),
    url(r'^update_book/$',Update_Book),
    url(r'^update_guidance/$',Update_Guidence),
    url(r'^lectures/$',Lectures),
    url(r'^training/$',Training),
    url(r'^projects/$',Projects),
    url(r'^patent/$',Patent_data),
    url(r'^Update_Patent/$',Update_Patent),
    url(r'^Update_Lectures/$',Update_Lectures),
    url(r'^Update_Training/$',Update_Training),
    url(r'^Update_Projects/$',Update_Projects),
    url(r'^approval/$',approval),
    url(r'^rnd_approval/$',rnd_approval),
    url(r'^mou/$',mou),
    url(r'^industrial_visit/$',IndustrialVisit),
    url(r'^guest_lecture/$',GuestLecture),
    url(r'^achievements/$',Achievements),
    url(r'^hobbyclub/$',hobbyclub),
    url(r'^schools/$',Schools),
    url(r'^events_organized/$',EventsOrganized),
    url(r'^aar_report/$',aar_report),
    url(r'^aar_approved_report/$',aar_approved_report),
    url(r'^report/$',report),
    url(r'^deanaar_report/$',deanaar_report),
    url(r'^website_aar/$',website_aar),
    url(r'^website_single/$',website_single),
    url(r'^director_report/$',director_report),
    url(r'^director_department_report/$',director_department_report),
    url(r'^delete_aar_employee/$',delete_aar_employee),
    url(r'^aar_dept_report/$',aar_dept_report),
    url(r'^aar_hod_dept_report/$',aar_hod_dept_report),
    url(r'^aar_emp_report/$',aar_emp_report),
    # url(r'^upload_file/$',upload_file),
    url(r'^get_components/$',getComponents),
    url(r'^emp_detail/$',emp_detail),
    url(r'^locking_unlocking/$',locking_unlocking),
    #url(r'^sBand/$',sBand),
    url(r'^aar_report_test/$',aar_report_test),
    url(r'^update_departmental_aar/$',update_departmental_aar),
    url(r'^increment_aar_settings/$',aar_increment_settings),
    url(r'^staff_shod/$',staff_shod),
    url(r'^staff_sdir/$',staff_sdir),
    url(r'^staff_a/$',staff_a),
    url(r'^staff_ahod/$',staff_ahod),
    url(r'^staff_adir/$',staff_adir),
    url(r'^staff_emg/$',staff_emg),
    url(r'^staff_emg_submit/$',staff_emg_submit),
    url(r'^emg_dropdown/$',staff_emg_hod_dropdown),
    url(r'^staff_emg_details/$',staff_emg_details),
    url(r'^emg_hod_submit/$',staff_emg_hod_submit),
    url(r'^emg_dir_dropdown/$',staff_emg_dir_dropdown),
    url(r'^emg_dir_details/$',staff_emg_dir_details),
    url(r'^emg_dir_submit/$',staff_emg_dir_submit),
    url(r'^staff_annual_increment_summary/$',staff_annual_increment_summary),
    url(r'^staff_a_report/$',staff_a_report),
    url(r'^staff_ahod_report/$',staff_ahod_report),
    url(r'^staff_adir_report/$',staff_adir_report),
    url(r'^staff_shod_report/$',staff_shod_report),
    url(r'^staff_sdir_report/$',staff_sdir_report),
    url(r'^staff_emg_report/$',staff_emg_report),
    url(r'^staff_emghod_report/$',staff_emghod_report),
    url(r'^staff_emgdir_report/$',staff_emgdir_report),
    url(r'^aar_dir_advance_report/$',aar_dir_advance_report),
    url(r'^aar_dir_advance_report_data/$',aar_dir_advance_report_data),
    url(r'^form_data/$',form_data),
    url(r'^insert_data/$',insert_data),
    url(r'^fc_app_advance_report/$',fc_app_advance_report),
    url(r'^recommend/$',recommend),
    url(r'^aar_emp_end_report/$',aar_emp_end_report),
    url(r'^rnd_update/$',rnd_update),
    url(r'^rnd_view/$',rnd_view),
    url(r'^rnd_reject/$',rnd_reject),
    url(r'^rnd_tabledata/$',rnd_tabledata),
    url(r'^DirReport/$',DirReport), 
    url(r'^web_rnd_tabledata/$',web_rnd_tabledata), 

]
