PRIORITY = [("H", "HIGH"), ("M", "MEDIUM"), ("L", "LOW")]
SCHEDULING = [("O","ONCE"),("D","DAILY"),("W","WEEKLY"),("M","MONTHLY"),("OT","OTHER")]
# PATTERN = re.compile("(0/91)?[7-9][0-9]{9}")
SENDER_EMAIL = "noreply@kiet.edu"
PASSWORD = "a4s3d2f1"
SMTP_SERVER = "smtp.gmail.com"
PORT = 587
SMS_USERNAME = "kietgzb"
SMS_PASSWORD = "kiet@123"
SMS_SENDERID = "KIETGZ"
SUBJECT_LENGTH = 78  # less than 78