# Generated by Django 2.0 on 2021-03-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0002_auto_20210305_1746'),
    ]

    operations = [

    ]
