# Generated by Django 2.0 on 2021-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0003_auto_20210305_1804'),
    ]

    operations = [
    ]
