# Generated by Django 2.0 on 2021-03-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__first__'),
        ('Registrar', '0005_auto_20210305_1813'),
    ]

    operations = [
    ]
