# Generated by Django 2.0 on 2021-03-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__first__'),
        ('Registrar', '0007_auto_20210305_1819'),
    ]

    operations = [
        
    ]
