PAYTM_ENVIRONMENT="PROD"
PAYTM_MERCHANT_KEY="4R#HKZU8o7xRRMSy"
PAYTM_MERCHANT_MID="KriIns08204252501061"
PAYTM_MERCHANT_WEBSITE="KriInsWEB"

PAYTM_DOMAIN = "pguat.paytm.com";
if PAYTM_ENVIRONMENT == 'PROD':
	PAYTM_DOMAIN = 'secure.paytm.in';

CHANNEL_ID="WEB"
INDUSTRY_TYPE_ID="PrivateEducation"
CALLBACK_URL="http://10.21.66.23:8000/website/payment_complete/"
PAYTM_REFUND_URL= 'https://'+PAYTM_DOMAIN+'/oltp/HANDLER_INTERNAL/REFUND'
PAYTM_STATUS_QUERY_URL= 'https://'+PAYTM_DOMAIN+'/oltp/HANDLER_INTERNAL/TXNSTATUS'
PAYTM_STATUS_QUERY_NEW_URL= 'https://'+PAYTM_DOMAIN+'/oltp/HANDLER_INTERNAL/getTxnStatus'
PAYTM_TXN_URL='https://'+PAYTM_DOMAIN+'/oltp-web/processTransaction'